---
name: main

on:
  release:
    types: [published]

jobs:
  docker-publish:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # Publishing Docker images only happens when a release published out of the
    # main branch
    if: >-
      github.event_name == 'release'
      && github.event.action == 'published'
      && (github.event.release.target_commitish == 'main'
         || github.event.release.target_commitish == 'master')
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up QEMU for more platforms supported by Buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7,linux/arm/v6,linux/arm64
          push: true
          tags:
            "ghcr.io/${{ github.repository_owner }}\
            /${{ github.event.repository.name }}:latest

            ghcr.io/${{ github.repository_owner }}\
            /${{ github.event.repository.name }}\
            :${{ github.event.release.tag_name }}"
